server:
  port: 8087
spring:
  application:
    name: mc-country
  data:
    redis:
      host: docker-redis-1
      port: 6379
app:
  cache:
    cache-names:
      - citiesOfCountry
    caches:
      citiesOfCountry:
        expiry: 1440m
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://mc-eureka-conteiner:8888/eureka/
  instance:
    hostname: localhost
