spring:
  data:
    redis:
      host: localhost
      port: 6379
app:
  cache:
    cache-names:
      - allCountries
      - allCitiesOfCountry
    caches:
      allCountries:
        expiry: 60s
      allCitiesOfCountry:
        expiry: 60s
